### ISSUE TITLE
Allow users to specify additional provides clauses

### ISSUE THREAD

**Issue by timothypratley** [cljsjs/boot-cljsjs#36]
deps.cljs can provide multiple namespaces, it would be useful for packaging some cljs projects like firebase and firebase-node

**Comment by Izzimach** [comment]
I actually need this myself for [react-pixi](https://github.com/Izzimach/react-pixi).

I hacked up a variant of `deps-cljs` that takes a vector of strings for the providers instead of a single string [here](https://gist.github.com/Izzimach/555c80143fef3588500bf78c0e3ed3ae). Does that seem reasonable?

Another method would be to modify `deps-cljs` so that it works both ways. That is, the provider could be a single string or a vector of strings. I'm not sure which is preferable TBH.

**Comment by timothypratley** [comment]
oooo nice!
That's great :)
Yes I think handling both cases would be useful for backwards compatibility.

**Comment by Deraen** [comment]
I don't see much value in generating deps.cljs in most of the cases, it is just as easy, or easier to write the `deps.cljs` by hand.

Simple deps.cljs: https://github.com/cljsjs/packages/blob/master/preact-compat/resources/deps.cljs
Additional entries generated from custom task: https://github.com/cljsjs/packages/blob/master/highlight/build.boot#L25-L41

I added note about limits of `deps-cljs` to packaging wiki: https://github.com/cljsjs/packages/wiki/Creating-Packages/_compare/414c39462f49e9b1cfb533b61658a30e964ecd79...2ec7521f6d0614edf4eb74f11ab762a68ff9f722
