### ISSUE TITLE
Trouble with tasks for DraftJS

### ISSUE THREAD

**Issue by abhi18av** [cljsjs/boot-cljsjs#37]
Hi @martinklepsch, I want to contribute Facebook's DraftJS to the CLJSJS project and I've created the extern and the file structure properly.

I've followed the instructions outlined in

[Boot CLJS Readme](https://github.com/cljsjs/boot-cljsjs)
[Creating Packages for CLJSJS](https://github.com/cljsjs/packages/wiki/Creating-Packages)
And below is the link for the gist file I created for build.boot task

[build.boot for draft cljsjs package](https://gist.github.com/abhi18av/fe2e3f5868471c4efb81d8675fbfe079)

<img width="1440" alt="screen shot 2016-08-22 at 10 54 40 am" src="https://cloud.githubusercontent.com/assets/12799326/17844514/f28eee2e-6857-11e6-8be8-5d6155c639bf.png">

I would really appreciate if you could help me out;p

**Comment by Deraen** [comment]
Looks like you have used React build.boot as a example? It is quite complex due to creating several jar files.

I would recommend using some other package as starting point. [auth0](https://github.com/cljsjs/packages/blob/master/auth0/build.boot) looks like what I think most packages without special requirements should look like.

(Do we point to React build.boot as example somewhere?)
